env:
  # WanDB
  WANDB_PROJECT: "LLM"
  WANDB_RUN_GROUP: 'KoreaMathWordProblem'
  WANDB_WATCH: ""
  # torch
  TORCH_DISTRIBUTED_DEBUG: "OFF"
  TORCHDYNAMO_VERBOSE: "1"
  TORCHDYNAMO_DISABLE: "1"
  PYTORCH_CUDA_ALLOC_CONF: "expandable_segments:True,roundup_power2_divisions:[32:256,64:128,256:64,>:32]"
  CUDA_DEVICE_ORDER: 'PCI_BUS_ID'
  OMP_NUM_THREADS: 2
output_dir: "/root/output_dir/gemma-3-12b-it/KoOrcaMath-14500"
model_name_or_path: 'google/gemma-3-12b-it'
# 데이터 전처리와 관련된 값
preprocessing_num_workers: 4
preprocessing_batch_size: 1000
max_length: 8196
data_preprocessor_type: "sft" # or pretrain
dataset_repo_ls:
  - "jp1924/korean-math-sft"
  - "jp1924/KoOrcaMath"
# data_name_map:
#   jp1924/KoOrcaMath: 
data_truncate_map:
  "jp1924/KoOrcaMath": 
    train: 14500
data_split_map:
  "jp1924/korean-math-sft":
    - validation
    - test
dataset_prefix:
  train:
    - train
  valid:
    - validation
    - test
  test:
    - test
# train & valid step과 관련된 값
per_device_train_batch_size: 64
gradient_accumulation_steps: 1
per_device_eval_batch_size: 32
eval_accumulation_steps: 1
num_train_epochs: 2
# train or valid or test 수행할지 말지 결정하는 값
do_train: true
# optim, scheduler와 관련된 값
learning_rate: 2e-5
lr_scheduler_type: cosine
warmup_ratio: 0.03
# optim: apollo_adamw
# optim_args: proj=random
# optim_target_modules: 
#   - 'model.language_model.layers.*.self_attn.*'
optim: adamw_torch_fused
# save & eval을 설정하는 값
torch_empty_cache_steps: 20
do_eval: true
do_predict: false
eval_strategy: 'steps'
eval_steps: 20
save_strategy: 'steps'
save_steps: 20
save_only_model: true
# logging과 관련된 값
report_to: 'wandb'
logging_strategy: 'steps'
logging_steps: 1
# 학습 최적화와 관련된 값
bf16: true
tf32: true
dtype: bfloat16
weight_decay: 0
torch_compile: true
use_liger_kernel: true
attn_implementation: flash_attention_2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
# dataloader와 관련된 값
dataloader_prefetch_factor: 10
dataloader_num_workers: 1
packing: false
# 기타 최적화
include_num_input_tokens_seen: true
remove_unused_columns: false
ddp_timeout: 18000000
seed: 42
run_name: "sft"
eval_harness_tasks: kmmlu
eval_on_start: true
########################
use_peft: false
lora_task_type: CAUSAL_LM
lora_r: 16
lora_target_modules: all-linear
lora_alpha: 16
lora_dropout: 0
use_rslora: false